sudo: required

services: 
- docker

language: go

go:
  - 1.9.x

before_install:
- chmod +x ./build.sh

install:
- ./build.sh

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file:
    - $TRAVIS_BUILD_DIR/securecookiecli
    - $TRAVIS_BUILD_DIR/securecookiecli.exe
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
